services:
  cerberus-db:
    container_name: cerberus-db
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=gris
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cerberus
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  cerberus-app:
    build: .
    container_name: cerberus-app
    restart: always
    environment:
      - POSTGRES_USER=gris
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cerberus
    ports:
      - "8080:8080"
    depends_on:
      - cerberus-db