services:
  postgres:
    container_name: postgres
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=gris
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cerberus
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql